name: Release

on:
  workflow_call:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 10
    concurrency: ${{ github.workflow }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version-file: .node-version

      - name: Update npm to latest
        run: |
          npm install --global npm@latest
          echo "Successfully updated npm to $(npm -v)"

      - name: Install dependencies
        run: npm ci

      - name: Set up Git
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Run release script
        id: release
        run: |
          npm run release
          echo "new_tag_name=$(git describe --abbrev=0)" >> "${GITHUB_OUTPUT}"

      - name: Push commit and tags
        env:
          NEW_TAG_NAME: ${{ steps.release.outputs.new_tag_name }}
        run: |
          # Extract the major version from the tag, e.g., "v1.2.3" -> "v1"
          MAJOR_VERSION_TAG=${NEW_TAG_NAME:0:2}

          pattern='^v[0-9]$'
          if [[ ! "${MAJOR_VERSION_TAG}" =~ $pattern ]]; then
            echo "Failed to extract the major version from the tag: ${NEW_TAG_NAME}"
            exit 1
          fi

          git push --follow-tags
          git tag --force --annotate --message "Release ${MAJOR_VERSION_TAG}" "${MAJOR_VERSION_TAG}"
          git push --tags --force origin "${MAJOR_VERSION_TAG}"

      - name: Create GitHub release
        env:
          NEW_TAG_NAME: ${{ steps.release.outputs.new_tag_name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${NEW_TAG_NAME}" \
            --notes "See the [changelog](https://github.com/${GITHUB_REPOSITORY}/blob/${NEW_TAG_NAME}/CHANGELOG.md) for details."

          release_url=$(gh release view "${NEW_TAG_NAME}" --json 'url' --jq '.url')
          echo "::notice::Released ${release_url}"
