name: Node.js Commit Lint (reusable)

on:
  workflow_call:

jobs:
  commitlint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: npm
      - run: npm --global install npm@latest
      - run: npm ci
      - uses: wagoid/commitlint-github-action@v5
        with:
          configFile: package.json
        env:
          NODE_PATH: ${{ github.workspace }}/node_modules
