name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        node-version: ["lts/*", "22", "20", "18", "16"]
        os: ["ubuntu-slim"]
    uses: ./.github/workflows/nodejs-test-reusable.yml
    with:
      node-version: ${{ matrix.node-version }}
      os: ${{ matrix.os }}
      node-version-coverage: "22"
      coverage-name: coverage
    permissions:
      contents: read

  show-coverage:
    needs: test
    runs-on: ubuntu-slim
    permissions:
      contents: read
    steps:
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: coverage
          path: downloaded/
      - run: ls -lR downloaded/

  lint:
    uses: ./.github/workflows/nodejs-lint-reusable.yml
    permissions:
      contents: read
