name: Node.js Test (reusable)

on:
  workflow_call:
    inputs:
      node-version:
        description: Node.js version
        required: false
        default: "lts/*"
        type: string
      node-version-coverage:
        description: Node.js version for test coverage
        required: false
        type: string
      os:
        description: OS name
        required: false
        default: ubuntu-latest
        type: string
      coverage-name:
        description: Name for coverage artifacts
        required: false
        default: coverage
        type: string
      coverage-path:
        description: Path to coverage artifacts
        required: false
        default: coverage/
        type: string

jobs:
  test:
    runs-on: ${{ inputs.os }}
    permissions:
      contents: read
    timeout-minutes: 30
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: ${{ inputs.node-version }}
          cache: npm

      - name: Get npm version
        id: npm-version
        run: |
          echo "current-version=$(npm -v | sed 's/^v//')" >> "${GITHUB_OUTPUT}"

          case $(node -v) in
            v16.*|v14.*|v12.*|v10.*)
              major_version=9
              ;;
            v18.*)
              major_version=10
              ;;
            *)
              echo "latest=true" >> "${GITHUB_OUTPUT}"
              echo "next-version=$(npm view npm version)" >> "${GITHUB_OUTPUT}"
              exit 0
              ;;
          esac
          version=$(npm view "npm@${major_version}" version --json | jq -r '.[-1]')
          echo "next-version=${version}" >> "${GITHUB_OUTPUT}"

      - name: |
          Update npm from ${{ steps.npm-version.outputs.current-version }} to ${{ steps.npm-version.outputs.next-version }}${{ steps.npm-version.outputs.latest && ' (latest)' }}
        env:
          current_npm_version: ${{ steps.npm-version.outputs.current-version }}
          next_npm_version: ${{ steps.npm-version.outputs.next-version }}
        run: |
          # HACK: Avoid the issue: https://github.com/npm/cli/issues/9151
          if [[ ${current_npm_version} == "10.9.7" ]]; then
            npm install --global "npm@10.9.8"
            echo "::warning::Updating npm to 10.9.8 first is required to avoid the issue: https://github.com/npm/cli/issues/9151"
          fi

          npm install --global "npm@${next_npm_version}"
          echo "New npm version: $(npm -v)"

      - name: Install dependencies
        run: npm ci

      - name: Run test
        run: npm test --ignore-scripts
        if: ${{ inputs.node-version != inputs.node-version-coverage }}

      - name: Run test with coverage
        run: npm run test:coverage --ignore-scripts
        if: ${{ inputs.node-version == inputs.node-version-coverage }}

      - name: Upload test coverage
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: ${{ inputs.node-version == inputs.node-version-coverage }}
        with:
          name: ${{ inputs.coverage-name }}
          path: ${{ inputs.coverage-path }}
          retention-days: 1
