name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        node-version: ["lts/*"]
        os: ["ubuntu-latest"]
    uses: ./.github/workflows/nodejs-test-reusable.yml
    with:
      node-version: ${{ matrix.node-version }}
      os: ${{ matrix.os }}

  lint:
    use: ./.github/workflows/nodejs-lint-reusable.yml
