name: Node.js Release

on:
  push:
    tags: ["**"]

jobs:
  release:
    uses: ./.github/workflows/nodejs-release-reusable.yml
    with:
      publish: false
      draft: false
    permissions:
      contents: write
      id-token: write
