name: Node.js Release

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  release:
    uses: ./.github/workflows/nodejs-release-reusable.yml
    with:
      publish: false
      draft: false
      update-semver-tag: true
    permissions:
      contents: write
      id-token: write
