name: Node.js Release

on:
  push:
    tags: ["**"]

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  release:
    uses: ./.github/workflows/nodejs-release-reusable.yml
    with:
      publish: false
    permissions:
      contents: write
