name: Ruby CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]

jobs:
  test:
    uses: ./.github/workflows/ruby-test-reusable.yml
    with:
      os: '["ubuntu-latest"]'

  test-minimum:
    uses: ./.github/workflows/ruby-test-reusable.yml
    with:
      os: '["ubuntu-latest"]'
      minimum-ruby-version: 2.7
