name: Ruby Release (reusable)

on:
  workflow_call:
    inputs:
      ruby-version:
        description: Ruby version
        required: false
        default: "ruby" # latest
        type: string

jobs:
  release:
    runs-on: ubuntu-slim
    permissions:
      contents: write
      id-token: write
    timeout-minutes: 10
    concurrency: ${{ github.workflow }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Ruby
        uses: ruby/setup-ruby@319994f95fa847cf3fb3cd3dbe89f6dcde9f178f # v1.295.0
        with:
          ruby-version: ${{ inputs.ruby-version }}
          bundler-cache: true

      - name: Publish gem
        uses: rubygems/release-gem@e9a6361a0b14562539327c2a02373edc56dd3169 # v1.1.4

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          new_tag="$(git describe --tags --abbrev=0)"
          gh release create "${new_tag}" --verify-tag --draft

          release_url=$(gh release view "${new_tag}" --json 'url' --jq '.url')
          echo "::notice::Created the draft release: ${release_url}"
