name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]

jobs:
  test:
    strategy:
      matrix:
        fail-fast: false
        node-version: ["14", "16", "18"]
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
    uses: ./.github/workflows/test-reusable.yml
    with:
      node-version: ${{ matrix.node-version }}
      os: ${{ matrix.os }}
